fix: build check only on pr

diff --git a/.github/workflows/build-check.yml b/.github/workflows/build-check.yml
--- a/.github/workflows/build-check.yml
+++ b/.github/workflows/build-check.yml
@@ -1,51 +1,48 @@
 name: CI
 
 on:
-    push:
-        branches:
-            - main
-    pull_request:
-        branches:
-            - main
-        types: [labeled]
+  pull_request:
+    branches:
+      - main
+    types: [labeled]
 
 jobs:
-    build:
-        if: github.event.action == 'labeled' && github.event.label.name == 'build ready'
-        name: Build Project
-        runs-on: ubuntu-latest
-        steps:
-            - name: Checkout code
-              uses: actions/checkout@v2
+  build:
+    if: github.event.action == 'labeled' && github.event.label.name == 'build ready'
+    name: Build Project
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-            - name: Set up Node.js
-              uses: actions/setup-node@v2
-              with:
-                  node-version: "24"
+      - name: Set up Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: "24"
 
-            - name: Install dependencies
-              run: npm install
+      - name: Install dependencies
+        run: npm install
 
-            - name: Build project
-              run: npm run build
+      - name: Build project
+        run: npm run build
 
-            - name: check if build folder exists
-              run: |
-                  if [ -d "build" ]; then
-                      echo "Build folder exists."
-                  else
-                      echo "Build folder does not exist."
-                      exit 1
-                  fi
+      - name: check if build folder exists
+        run: |
+          if [ -d "build" ]; then
+              echo "Build folder exists."
+          else
+              echo "Build folder does not exist."
+              exit 1
+          fi
 
-            - name: List build folder contents
-              run: ls -la build
+      - name: List build folder contents
+        run: ls -la build
 
-            - name: Verify build output
-              run: |
-                  if [ -f "build/index.html" ]; then
-                      echo "Build output is valid."
-                  else
-                      echo "Build output is invalid."
-                      exit 1
-                  fi
+      - name: Verify build output
+        run: |
+          if [ -f "build/index.html" ]; then
+              echo "Build output is valid."
+          else
+              echo "Build output is invalid."
+              exit 1
+          fi
